version: "3.8"

services:
  jupiter:
    container_name: jupiter
    build: ./jupiter
    volumes:
      - ./jupiter:/jupiter
    ports:
      - "3000:3000"
  mercury:
    container_name: mercury
    build: ./mercury
    volumes:
      - ./mercury:/mercury
    ports:
      - "4000:4000"
